book/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"books", views.BookViewSet)
router.register(r"authors", views.AuthorViewSet)
router.register(r"categories", views.CategoryViewSet)

app_name = "book"
urlpatterns = [
    path("", include(router.urls)),
    path("home/", views.home_page, name="home"),
    path("author/", views.author_view, name="author"),
    path("author-edit/<int:id>", views.author_edit_view, name="author edit"),
    path("author-register/", views.author_register_view, name="author register"),
    path("author-delete/<int:id>", views.author_delete_view, name="author delete"),
    path("category/", views.category_view, name="category"),
    path("category-edit/<int:id>", views.category_edit_view, name="category edit"),
    path("category-register/", views.category_register_view, name="category register"),
    path(
        "category-delete/<int:id>", views.category_delete_view, name="category delete"
    ),
    path("book-shelf/", views.book_shelf_view, name="book shelf"),
    path("book-register/", views.book_register_view, name="book register"),
    path("book-edit/<int:id>", views.book_edit_view, name="book edit"),
    path("book-detail/<int:id>", views.book_detail_view, name="book detail"),
    path("book-delete/<int:id>", views.book_delete_view, name="book delete"),
]

bookProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

djangotask/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
]

libraryProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
]

book/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    published_date = models.DateField(auto_now=False)
    categories = models.ManyToManyField(Category)
    authors = models.ManyToManyField(Author)

    def __str__(self):
        return self.title

book/forms.py
from django import forms
from .models import Author, Category, Book
from django.forms.widgets import CheckboxSelectMultiple
from django.core.exceptions import ValidationError


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'title',
            'published_date',
            'categories',
            'authors'
        ]

        widgets = {
            'published_date': forms.DateInput(attrs={"type": "date"}),
            'categories': CheckboxSelectMultiple(),
            'authors': CheckboxSelectMultiple()
        }

        labels = {
            'title': 'Title',
            'published_date': 'Published Date',
            'categories': 'Category',
            'authors': 'Author'
        }

    def clean(self):
        try:
            title = self.cleaned_data.get('title')
            authors = self.cleaned_data.get('authors')
            authors = list(authors.values_list('name', flat=True))
            same_books = list(Book.objects.filter(
                title=title).exclude(id=self.instance.id))  # タイトルが同じ本のリストを作成
            for same_book in same_books:  # タイトルが同じ本の著者を順に調べる
                exist_authors = list(
                    same_book.authors.values_list('name', flat=True))  # 存在する著者のリストを作成
                if exist_authors == authors:  # 送信した著者と存在する著者が一致した場合エラー
                    raise ValidationError("Error")
        except:
            raise ValidationError("Error")

book/views.py
import csv
import datetime

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect, render
from rest_framework.viewsets import ModelViewSet

from .forms import AuthorForm, BookForm, CategoryForm
from .models import Author, Book, Category
from .serializers import AuthorSerializer, BookSerializer, CategorySerializer


# Create your views here.
def home_page(request):
    return render(request, "book/index.html")


def author_view(request):
    authors = Author.objects.all()
    return render(request, "book/author.html", {"authors": authors})


def author_edit_view(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=author)
        if form.is_valid():
            form.save()
            messages.success(request, "Update submission succesfull")
            return redirect("book:author")
        else:
            messages.error(request, "Sorry, same author already exists")
            return redirect("book:author")
    else:
        form = AuthorForm(instance=author)
    return render(request, "book/author_edit.html", dict(form=form, id=id))


def author_register_view(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Form submission successful")
            return redirect("book:author")
        else:
            messages.error(request, "Sorry, same author already exists")
            return redirect("book:author")
    else:
        form = AuthorForm()
    return render(request, "book/author_register.html", {"form": form})


def author_delete_view(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        author.delete()
        messages.success(request, "Form submission successful")
        return redirect("book:author")
    return render(request, "book/author_delete.html", {"author": author})


def category_view(request):
    categories = Category.objects.all()
    return render(request, "book/category.html", {"categories": categories})


def category_edit_view(request, id):
    category = Category.objects.get(id=id)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, "Update submission succesfull")
            return redirect("book:category")
        else:
            messages.error(request, "Sorry, same category already exists")
            return redirect("book:category")
    else:
        form = CategoryForm(instance=category)
    return render(request, "book/category_edit.html", dict(form=form, id=id))


def category_register_view(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Form submission successful")
            return redirect("book:category")
        else:
            messages.error(request, "Sorry, same category already exists")
            return redirect("book:category")
    else:
        form = CategoryForm()
    return render(request, "book/category_register.html", {"form": form})


def category_delete_view(request, id):
    category = Category.objects.get(id=id)
    if request.method == "POST":
        category.delete()
        messages.success(request, "Form submission successful")
        return redirect("book:category")
    return render(request, "book/category_delete.html", {"category": category})


def book_shelf_view(request):
    books = Book.objects.all()
    if request.method == "POST":
        if "csv-export" in request.POST:
            response = HttpResponse(content_type="text/csv")
            today_string = datetime.datetime.today().strftime("%x")

            # ファイル名　'book_detail_01_16_21.csv'
            response[
                "Content-Disposition"
            ] = f'attachment; filename="book_detail_{today_string}.csv"'

            writer = csv.writer(response)
            # ヘッダー
            writer.writerow(["No.", "Title", "Published Date", "Author", "Category"])
            for index, book in enumerate(
                Book.objects.all().prefetch_related("authors", "categories"), 1
            ):
                authors = ", ".join([author.name for author in book.authors.all()])
                categories = ", ".join(
                    [category.name for category in book.categories.all()]
                )

                # ""で囲んで表示したい場合は f'"{authors}"'

                writer.writerow(
                    [index, book.title, book.published_date, authors, categories]
                )
            return response
    return render(request, "book/book_shelf.html", {"books": books})


def book_register_view(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Form submission successful")
            return redirect("book:book shelf")
        else:
            messages.error(request, "Sorry, there is an error.")
            return redirect("book:book shelf")
    else:
        form = BookForm()
    return render(request, "book/book_register.html", {"form": form})


def book_edit_view(request, id):
    book = Book.objects.get(id=id)
    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, "Update submission succesfull")
            return redirect("book:book shelf")
        else:
            messages.error(request, "Sorry, there is an error.")
            return redirect("book:book shelf")
    else:
        form = BookForm(instance=book)
    return render(request, "book/book_edit.html", dict(form=form, id=id))


def book_detail_view(request, id):
    book = Book.objects.get(id=id)
    return render(request, "book/book_detail.html", {"book": book})


def book_delete_view(request, id):
    book = Book.objects.get(id=id)
    if request.method == "POST":
        book.delete()
        messages.success(request, "Form submission successful")
        return redirect("book:book shelf")
    return render(request, "book/book_delete.html", {"book": book})


class BookViewSet(ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class AuthorViewSet(ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer


class CategoryViewSet(ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

book/templates/book/author.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Author</h1>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<a href="{% url 'book:author register' %}">Add Author</a>
<table>
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        {% for author in authors %}
        <tr>
            <th>{{ author.name }}</th>
            <th> <a href="{% url 'book:author edit' author.id %}"><span>Edit</span></a></th>
            <th> <a href="{% url 'book:author delete' author.id %}"><span>Delete</span></a></th>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}]

book/templates/book/author_delete.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Author Delete</h1>
<p>Confirm deleting</p>
<p>Are you sure you want to delete " {{ author.name }} "?(<a href="{% url 'book:author' %}"><span>Back to
            List</span></a>)
</p>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
{% endblock content %}]

book/templates/book/author_register.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Author Register</h1>
<form method="POST">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <fieldset>
        <legend>Author Register</legend>
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label_tag }}
            {{ field }}
        </div>
        {% endfor %}
        <button type="submit">Register</button>
    </fieldset>
</form>
{% endblock content %}]

book/templates/book/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'book/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Book Manager</title>
</head>

<body>
    <nav>
        <form action="{% url 'book:home' %}" method="post">
            {% csrf_token %}
            <button type="submit">Home</button>
        </form>
        <form action="{% url 'book:book shelf' %}" method="post">
            {% csrf_token %}
            <button type="submit">Book Shelf</button>
        </form>
        <form action="{% url 'book:author' %}" method="post">
            {% csrf_token %}
            <button type="submit">Author</button>
        </form>
        <form action="{% url 'book:category' %}" method="post">
            {% csrf_token %}
            <button type="submit">Category</button>
        </form>
    </nav>
    {% block content %}

    {% endblock content %}
</body>

</html>

book/templates/book/book_delete.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Book Delete</h1>
<p>Confirm deleting</p>
<p>Are you sure you want to delete " {{ book.title }} "?</p>
<p><a href="{% url 'book:book detail' book.id %}">Back to Detail</a></p>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
{% endblock content %}

book/templates/book/book_edit.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Book Edit</h1>
<form method="POST">
    <fieldset>
        <legend>Book Editor</legend>
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label_tag }}
            {{ field }}
            {% if field.name == "categories" %}
            <p><a href="{% url 'book:category register' %}">Add Category from here</a></p>
            {% elif field.name == "authors" %}
            <p><a href="{% url 'book:author register' %}">Add Author from here</a></p>
            {% endif %}
        </div>
        {% endfor %}
    </fieldset>
    <button type="submit">Update</button>
</form>
{% endblock content %}

book/templates/book/book_register.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Book Register</h1>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="csv">
    <button type="submit" name="csv-import">Upload</button>
</form>
<form method="POST">
    {% csrf_token %}
    <button type="submit" name="export-template">Download upload file(CSV)</button>
</form>
<form method="POST">
    <fieldset>
        <legend>Book Register</legend>
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label_tag }}
            {{ field }}
            {% if field.name == "categories" %}
            <p><a href="{% url 'book:category register' %}">Add Category from here</a></p>
            {% elif field.name == "authors" %}
            <p><a href="{% url 'book:author register' %}">Add Author from here</a></p>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" name="register-form">Submit</button>
    </fieldset>
</form>
{% endblock content %}

book/templates/book/book_shelf.html
{% extends "./base.html" %}

{% block content %}
<h1 class='title'>Book Shelf</h1>
<div class='content'>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <p><a href="{% url 'book:book register' %}">Add Book</a></p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" name="csv-export">Download Book Details(CSV)</button>
    </form>
    <table>
        <thead>
            <tr>
                <th>Title</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{ book.title }}</td>
                <td> <a href="{% url 'book:book edit' book.id %}"><span>Edit</span></a></td>
                <td> <a href="{% url 'book:book detail' book.id %}"><span>Detail</span></a></td>
                <td> <a href="{% url 'book:book delete' book.id %}"><span>Delete</span></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

book/templates/book/category.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Category</h1>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<a href="{% url 'book:category register' %}">Add Category</a>
<table>
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        {% for category in categories %}
        <tr>
            <th>{{ category.name }}</th>
            <th> <a href="{% url 'book:category edit' category.id %}"><span>Edit</span></a></th>
            <th> <a href="{% url 'book:category delete' category.id %}"><span>Delete</span></a></th>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

book/templates/book/category_delete.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Category Delete</h1>
    <p>Confirm deleting</p>
    <p>Are you sure you want to delete " {{ category.name }} "?(<a href="{% url 'book:category' %}"><span>Back to
                List</span></a>)
    </p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
{% endblock content %}

book/templates/book/category_edit.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Category Edit</h1>
    <form method="POST">
        <fieldset>
            <legend>Category Editor</legend>
            {% csrf_token %}
            {% for field in form %}
            <div>
                {{ field.label_tag }}
                {{ field }}
            </div>
            {% endfor %}
            <button type="submit">Update</button>
        </fieldset>
    </form>
{% endblock content %}

book/templates/book/category_register.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1 class='title'>Category Register</h1>
<form method="POST">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <fieldset>
        <legend>Category Register</legend>
        {% csrf_token %}
        {% for field in form %}
        <div>
            {{ field.label_tag }}
            {{ field }}
        </div>
        {% endfor %}
        <button type="submit">Register</button>
    </fieldset>
</form>
{% endblock content %}

book/templates/book/login.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1>Log In</h1>
<form action="{% url 'book:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Log In">
</form>
{% endblock content %}

book/templates/book/signup.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1>Signup</h1>
<form action="{% url 'book:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Sign Up">
</form>
{% endblock content %}